import './globals.css'
import type { Metadata } from 'next'
import { Inter, Limelight } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const limeLight = Limelight({ weight: "400", subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={limeLight.className}>{children}</body>
    </html>
  )
}
